### ISSUE TITLE
What should I do with the ERROR?

### ISSUE THREAD

**Issue by ConcealedBlade** [stephenmk/jitenbot#7]
Following is my output. Thanks in advance!

>jitenbot.py jitenon-kotowaza
17:52:02 Scraping https://kotowaza.jitenon.jp/cat/gojuon.php
        Discovering cached file 7018
17:56:15 Found 6951 entry pages
Traceback (most recent call last):
 File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 124, in <module>
    main()
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 114, in main
    crawler.read_pages()
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\crawlers\base\crawler.py", line 30, in read_pages
    entry.set_page(page)
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\entries\base\jitenon_entry.py", line 35, in set_page
    self.__set_column(colname, colval)
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\entries\base\jitenon_entry.py", line 79, in __set_column
    attr_name = column_map[colname]
                ~~~~~~~~~~^^^^^^^^^
KeyError: '使用漢字'

**Comment by stephenmk** [comment]
Thank you for reporting this. It looks like an extra "使用漢字" row has been added to the tables on jitenon.jp. This row did not exist when I wrote the program, so the program doesn't know how to handle the information.

I have updated the program and I think the issue should be solved, but I need to download all of the data again to verify that none of the pages will cause any errors. I tested a few pages and it seems to work (see the images below).

[You can view the changes to the code here](https://github.com/stephenmk/jitenbot/commit/b2384defd1e4ba9360015ae894db1db057219d0c).

![aikotobanisuru](https://github.com/stephenmk/jitenbot/assets/8003332/7596db84-4b2f-47c9-971b-854bd77248c8)
![aikotobanisuru2](https://github.com/stephenmk/jitenbot/assets/8003332/4b029ef9-99f3-4522-890e-376ada3831fa)

**Comment by ConcealedBlade** [comment]
I encounter another error now.

```
D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0>jitenbot.py jitenon-kotowaza
00:46:52 Scraping https://kotowaza.jitenon.jp/cat/gojuon.php
        Discovering cached file 7018
00:50:35 Found 6951 entry pages
        Reading page 6951/6951
00:54:38 Initializing build directory `C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\yomichan_build`
        Creating Yomichan terms for entry 6951/6951
00:54:55 Exporting 8560 JSON terms
        Writing terms to term bank 5/5
00:54:56 Archiving data to ZIP file...
00:54:56 Dictionary file saved to `C:\Users\Administrator\Documents\jitenbot\yomichan\故事・ことわざ・慣用句オンライン.zip`
00:54:56 Initializing build directory `C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\mdict_build`
Traceback (most recent call last):
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 124, in <module>
    main()
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 119, in main
    crawler.make_mdict_dictionary(
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\crawlers\base\crawler.py", line 45, in make_mdict_dictionary
    exporter.export(self._entries, media_dir, icon_file)
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\mdict\exporters\base\exporter.py", line 24, in export
    self._init_description_file(entries)
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\mdict\exporters\base\exporter.py", line 62, in _init_description_file
    "{{revision}}", self._get_revision(entries))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\mdict\exporters\base\jitenon.py", line 10, in _get_revision
    revision = modified_date.strftime("%Y年%m月%d日閲覧")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error**
```

I would recommend adding this code to the top of jitenbot.py. Anyway, it works in my computer.

```
import locale
locale.setlocale(locale.LC_CTYPE,'chinese')

```

**Comment by ConcealedBlade** [comment]
Error again with jitenon-yoji

```
D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0>jitenbot.py jitenon-yoji
01:27:48 Scraping https://yoji.jitenon.jp/cat/gojuon.html
        Discovering cached file 6504
01:27:53 Found 6441 entry pages
Error: table data not found in page.
Try deleting and redownloading file:
        C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\jitenon\yoji\yojif\2516_html-2d1c879a565d2eb0d244654755770c1a.html

        Reading page 6441/6441
01:31:31 Initializing build directory `C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\yomichan_build`
Traceback (most recent call last):r entry 952/6440
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 126, in <module>
    main()
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 118, in main
    crawler.make_yomichan_dictionary(
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\crawlers\base\crawler.py", line 41, in make_yomichan_dictionary
    exporter.export(self._entries, media_dir, validate)
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\yomichan\exporters\base\exporter.py", line 31, in export
    terms = self.__get_terms(entries)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\yomichan\exporters\base\exporter.py", line 81, in __get_terms
    new_terms = self._terminator.make_terms(entry)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\yomichan\terms\base\terminator.py", line 24, in make_terms
    glossary = self._glossary(entry)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\yomichan\terms\base\jitenon.py", line 15, in _glossary
    glossary = self._glossary_maker.make_glossary(entry, self._image_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\yomichan\glossary\jitenon.py", line 148, in make_glossary
    self._add_internal_links(soup, entry)
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\yomichan\glossary\jitenon.py", line 31, in _add_internal_links
    ref_entry = entry.ID_TO_ENTRY[ref_entry_id]
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 6812
```

**Comment by ConcealedBlade** [comment]
jitenon-yoji has many missing entries in "五十音検索". 
From https://yoji.jitenon.jp/yojim/6812.html to https://yoji.jitenon.jp/yojim/6905.html
Why not crawl the words by increasing the  end numbers in the URL so that there are no missing words?

**Comment by stephenmk** [comment]
```
**UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error**
```

This is a surprising error. I didn't expect that Python's standard library would ever produce errors due to unicode. Thanks for letting me know.

```
Error: table data not found in page.
Try deleting and redownloading file:
        C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\jitenon\yoji\yojif\2516_html-2d1c879a565d2eb0d244654755770c1a.html
```

You should delete the file located at `C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\jitenon\yoji\yojif\2516_html-2d1c879a565d2eb0d244654755770c1a.html`, and jitenbot will redownload it the next time you run the program.

> jitenon-yoji has many missing entries in "五十音検索".

Yes, I just noticed this as well. The program expected to find entry [6812](https://yoji.jitenon.jp/yojim/6812.html) (春風風人), but it cannot find it because the entry is new and still missing from the 五十音検索.

The problem with increasing the end numbers in the URL is that the end letter in the sudirectory name also changes. `yoji.jitenon.jp/yojig` contains entries 3001-3500, `yojih` contains entries 3501-4000, but `yojim` seems to contain entries 6001-6905. So the number of entries in each subdirectory isn't the same. Also, some entries will simply redirect to a different entry (`yojim/6001.html` redirects to `yojie/2323.html`), so there is a risk of creating duplicates if this is not considered.

I need to think about this and research all the options. There may be a simple solution.

**Comment by ConcealedBlade** [comment]
> You should delete the file located at C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\jitenon\yoji\yojif\2516_html-2d1c879a565d2eb0d244654755770c1a.html, and jitenbot will redownload it the next time you run the program.

I do what you say, and I get such output.

```
D:\Users\smallshrimp\Downloads\Compressed\jitenbot-2023.08.14.0>jitenbot.py jitenon-kokugo
01:38:06 Scraping https://kokugo.jitenon.jp/cat/gojuonindex.php
01:47:36 Scraping https://kokugo.jitenon.jp/word/p12188 ...01:47:37 OK
        Discovering cached file 38614
02:03:05 Found 37172 entry pages
Traceback (most recent call last):
  File "D:\Users\smallshrimp\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 126, in <module>
    main()
  File "D:\Users\smallshrimp\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 116, in main
    crawler.read_pages()
  File "D:\Users\smallshrimp\Downloads\Compressed\jitenbot-2023.08.14.0\bot\crawlers\base\crawler.py", line 30, in read_pages
    entry.set_page(page)
  File "D:\Users\smallshrimp\Downloads\Compressed\jitenbot-2023.08.14.0\bot\entries\base\jitenon_entry.py", line 36, in set_page
    self.__set_column(colname, colval)
  File "D:\Users\smallshrimp\Downloads\Compressed\jitenbot-2023.08.14.0\bot\entries\base\jitenon_entry.py", line 80, in __set_column
    attr_name = column_map[colname]
                ~~~~~~~~~~^^^^^^^^^
KeyError: '分類'
```

**Comment by ConcealedBlade** [comment]
Similar error exist when run jitenbot.py jitenon-kokugo. It also seems to be because of the updates to the website.

```
D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0>jitenbot.py jitenon-kokugo
01:38:06 Scraping https://kokugo.jitenon.jp/cat/gojuonindex.php
01:47:36 Scraping https://kokugo.jitenon.jp/word/p12188 ...01:47:37 OK
        Discovering cached file 38614
02:03:05 Found 37172 entry pages
Traceback (most recent call last):
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 126, in <module>
    main()
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\jitenbot.py", line 116, in main
    crawler.read_pages()
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\crawlers\base\crawler.py", line 30, in read_pages
    entry.set_page(page)
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\entries\base\jitenon_entry.py", line 36, in set_page
    self.__set_column(colname, colval)
  File "D:\Users\Administrator\Downloads\Compressed\jitenbot-2023.08.14.0\bot\entries\base\jitenon_entry.py", line 80, in __set_column
    attr_name = column_map[colname]
                ~~~~~~~~~~^^^^^^^^^
KeyError: '分類'

```

**Comment by stephenmk** [comment]
> I do what you said, and I get such output.

Yes, I apologize for not being more clear. There were two errors in your post.

Error 1: `Error: table data not found in page.`
Error 2: `KeyError: 6812`

By deleting the file, only error 1 was fixed. I still need to think about how to fix error 2.

> Maybe it's down to the fact that the original page was blank?
> https://yoji.jitenon.jp/yojim/2516.html

Your link is incorrect. The subdirectory letter also changes. yoji**f** rather than yoji**m**
https://yoji.jitenon.jp/yojif/2516.html

> Similar error exist when running jitenbot.py jitenon-kokugo. It also seems to be because of the updates to the website.

Yes, I will need to update the program. This is the same as the original `使用漢字` problem

**Comment by ConcealedBlade** [comment]
There are so many dictionaries in kotobank. Would you like to update jitenbot in the future to support crawling this site and making mdx(yomichan) automatically?

**Comment by ConcealedBlade** [comment]
<img width="1016" alt="image" src="https://github.com/stephenmk/jitenbot/assets/63355926/5cfebe37-8be1-42ea-a40b-dfb18b8f4689">
Jitenon-kotowaza's entries are useless and hard to be searched. Is the program designed to do this or is it a mistake?

**Comment by stephenmk** [comment]
> After downloading the latest code and running it...
> KeyError: 61916.
> It’s déjà vu all over again

You are missing the entry for [61916](https://kokugo.jitenon.jp/word/p61916), but this entry is not missing from the 五十音検索. So you should be able to download it.

I think it was probably added while you were downloading the data.

Try deleting this folder and running `jitenon-kokugo` again:
`C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\jitenon\kokugo\cat`

> There are so many dictionaries in kotobank, whose anti-crawler strategy is light-handed. Would you like to update jitenbot in the future to support crawling this site and making mdx(yomichan) automatically?

I know. Maybe someday.

> Jitenon-kotowaza's entries are useless and hard to be searched. Is the program designed to do this or is it a mistake?

The entries beginning with @ are hidden in GoldenDict unless you look at the dictionary headword list directly. I don't know how it displays in other clients.

You should be able to search for words normally. If you search for `お家がらがら`, can you not find that entry?

**Comment by ConcealedBlade** [comment]
```
You are missing the entry for [61916](https://kokugo.jitenon.jp/word/p61916), but this entry is not missing from the 五十音検索. So you should be able to download it.

I think it was probably added while you were downloading the data.
```
No, I hadn't done it.
I find that I didn't download p61916 for some unknown cause.
What should I do then to solve the problem?

`You should be able to search for words normally. If you search for お家がらがら, can you not find that entry?`

Sorry, man. Forgive my oversight and haste, and normal entries do exist.

**Comment by ConcealedBlade** [comment]
> Try deleting this folder and running jitenon-kokugo again:
> C:\Users\Administrator\AppData\Local\jitenbot\jitenbot\Cache\jitenon\kokugo\cat

All the same... The program is still not going to download p61916.

**Comment by stephenmk** [comment]
I updated the program to fetch the yoji entries that are not indexed in the 五十音検索 (entries 6812 through 6905).

I also updated the program to print a warning when entries are not found from Jitenon. It shouldn't crash and produce an error anymore when it cannot find all the entries.

**Comment by ConcealedBlade** [comment]
Thanks a million! Your prompt answers are reassuring and your program is a fat lot of help.
